# Generated by Django 3.1 on 2020-09-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0003_auto_20200914_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='estancia',
            field=models.CharField(default='30', max_length=25),
        ),
        migrations.AddField(
            model_name='negocio',
            name='turno',
            field=models.CharField(default='30', max_length=25),
        ),
        migrations.AddField(
            model_name='visitas',
            name='fecha_visita',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='positivo',
            name='celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='positivo',
            name='fecha_test',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='celular',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
