# Generated by Django 3.1 on 2020-09-17 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proapp', '0004_auto_20200917_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitas',
            name='negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='proapp.negocio'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='estancia',
            field=models.DecimalField(decimal_places=0, default=30, max_digits=25),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='turno',
            field=models.DecimalField(decimal_places=0, default=6, max_digits=25),
        ),
        migrations.AlterField(
            model_name='positivo',
            name='celular',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='positivo',
            name='fecha_test',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='celular',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='fecha_visita',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proapp.negocio')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proapp.visitas')),
            ],
        ),
    ]
