# Generated by Django 3.1 on 2020-09-18 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0005_auto_20200917_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proapp.positivo'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='fecha_visita',
            field=models.DateField(auto_now=True),
        ),
    ]
