# Generated by Django 3.1 on 2020-09-18 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0006_auto_20200917_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cercano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_cercano', models.DecimalField(decimal_places=0, max_digits=20)),
                ('avisado', models.BooleanField(default=False)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proapp.aviso')),
            ],
        ),
    ]
