# Generated by Django 3.1 on 2020-09-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0007_cercano'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='empleado',
            field=models.BooleanField(default=False),
        ),
    ]
