# Generated by Django 3.1 on 2020-09-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0008_visitas_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='fecha_visita',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
